// FILE: pages/terms.tsx
import React from "react";
import Head from "next/head";
import Link from "next/link";

export default function TermsPage() {
  return (
    <>
      <Head>
        <title>Terms of Use – StickAINote</title>
        <meta
          name="description"
          content="Terms of Use for StickAINote. Please read these terms carefully before using the service."
        />
      </Head>

      <main
        style={{
          minHeight: "100vh",
          background: "#020617",
          color: "white",
          padding: "24px 16px",
          boxSizing: "border-box",
        }}
      >
        <div
          style={{
            maxWidth: 800,
            margin: "0 auto",
          }}
        >
          <h1 style={{ fontSize: 28, marginBottom: 12 }}>Terms of Use</h1>

          <p style={{ fontSize: 14, lineHeight: 1.6 }}>
            Welcome to StickAINote. By accessing or using our website and
            software, you agree to be bound by these Terms of Use. If you do
            not agree to these terms, please do not use the service.
          </p>

          <h3 style={{ fontSize: 18, marginTop: 24, marginBottom: 8 }}>
            1. Use of Service
          </h3>
          <p style={{ fontSize: 14, lineHeight: 1.6 }}>
            StickAINote provides AI-powered note-taking and thoughtboard
            capabilities. You must use the service in compliance with all
            applicable laws and regulations. You agree not to misuse the
            service, including attempting to disrupt its operation or accessing
            it using unauthorized methods.
          </p>

          <h3 style={{ fontSize: 18, marginTop: 24, marginBottom: 8 }}>
            2. User Accounts
          </h3>
          <p style={{ fontSize: 14, lineHeight: 1.6 }}>
            To access certain features, you may need to create an account. You
            are responsible for maintaining the confidentiality of your account
            credentials and for all activities that occur under your account.
            Please notify us immediately of any unauthorized use.
          </p>

          <h3 style={{ fontSize: 18, marginTop: 24, marginBottom: 8 }}>
            3. AI Content and Liability
          </h3>
          <p style={{ fontSize: 14, lineHeight: 1.6 }}>
            The content generated by the AI features within StickAINote is
            automated and may not always be accurate. You acknowledge that
            StickAINote is a productivity tool and not a source of professional
            advice. We serve the content "as is" and disclaim all liability
            regarding the accuracy or reliability of AI-generated outputs.
          </p>

          <h3 style={{ fontSize: 18, marginTop: 24, marginBottom: 8 }}>
            4. Subscriptions and Payments
          </h3>
          <p style={{ fontSize: 14, lineHeight: 1.6 }}>
            Some features are available only through a paid subscription. Unless
            otherwise stated, subscriptions renew automatically. You may cancel
            your subscription at any time; however, refunds are provided at our
            sole discretion and in accordance with our refund policy.
          </p>

          <h3 style={{ fontSize: 18, marginTop: 24, marginBottom: 8 }}>
            5. Termination
          </h3>
          <p style={{ fontSize: 14, lineHeight: 1.6 }}>
            We reserve the right to suspend or terminate your access to
            StickAINote at any time, without notice, for conduct that we believe
            violates these Terms or is harmful to other users, us, or third
            parties, or for any other reason.
          </p>

          <h3 style={{ fontSize: 18, marginTop: 24, marginBottom: 8 }}>
            6. Changes to Terms
          </h3>
          <p style={{ fontSize: 14, lineHeight: 1.6 }}>
            We may modify these Terms at any time. Your continued use of
            StickAINote following the posting of changes constitutes your
            acceptance of such changes. Please review the Terms periodically.
          </p>

          <p style={{ marginTop: 24, fontSize: 14, lineHeight: 1.6 }}>
            For details on how we handle your data, please review our{" "}
            <Link href="/privacy" style={{ textDecoration: "underline", color: "white" }}>
              Privacy Policy
            </Link>
            .
          </p>

          <p style={{ marginTop: 24, fontSize: 13 }}>
            <Link href="/" style={{ textDecoration: "underline", color: "white" }}>
              ← Back to home
            </Link>
          </p>
        </div>
      </main>
    </>
  );
}
